/** Chinese interface text for this tool (src/lib/i18n/toolText.js). */
export default {
  "Printed squares = {0} × {1} = {2}": "打印方格数 = {0} × {1} = {2}",
  "Board size: {0}×{1} mm": "标定板尺寸：{0}×{1} mm",
  "For best results, mount on rigid backing (foam board, etc.)":
    "为获得最佳效果，请贴在硬质背板（如泡沫板）上",
  "Verify printed dimensions with a ruler before use":
    "使用前请用尺子核对打印尺寸",
  "Use a laser printer for best precision and contrast":
    "使用激光打印机可获得最佳精度和对比度",
  "- disable “Fit to page”": "，并关闭“适合页面”",
  "Print at": "按",
  "Use high-quality white paper (minimum 80gsm recommended)":
    "使用优质白纸（建议至少 80 克）",
  "Printing instructions": "打印说明",
  "Scale is proportional for display. Physical dimensions are preserved in the exported PDF.":
    "预览按比例缩放显示，导出的 PDF 保持实际物理尺寸。",
  "Preview Note:": "预览说明：",
  "Printable calibration target preview": "可打印标定板预览",
  "Live preview": "实时预览",
  "Download PDF": "下载 PDF",
  "Key Dot (mm)": "定位点（mm）",
  "Center Hub (mm)": "中心圆（mm）",
  "Gap 2 Angle (°)": "缺口 2 角度（°）",
  "Gap 1 Angle (°)": "缺口 1 角度（°）",
  "Ring Width (mm)": "圆环宽度（mm）",
  "Outer Diameter (mm)": "外径（mm）",
  "Ring with arc gaps": "带弧形缺口的圆环",
  "Border Stroke (mm)": "边框线宽（mm）",
  "Center Hole (mm)": "中心孔（mm）",
  "Ring Count": "圆环数",
  "Bullseye configuration": "靶心标志设置",
  "(rows + 1) × (cols + 1)": "（行数 + 1）×（列数 + 1）",
  "inner corners": "内角点",
  "OpenCV detects": "OpenCV 检测的是",
  "Square size (mm)": "方格边长（mm）",
  "Label size (pt)": "标签字号（pt）",
  "Center dot (mm)": "中心点（mm）",
  "Grid columns": "网格列数",
  "Grid rows": "网格行数",
  "Rotation step (°)": "旋转步长（°）",
  "Segment angle (°)": "扇区角度（°）",
  "Ring width (mm)": "圆环宽度（mm）",
  "Outer diameter (mm)": "外径（mm）",
  "Segmented marker configuration": "分段标志设置",
  "Columns (inner corners)": "列数（内角点）",
  "Rows (inner corners)": "行数（内角点）",
  "Chessboard configuration": "棋盘格设置",
  "Margin (mm)": "页边距（mm）",
  "Letter (8.5×11 in)": "Letter（8.5×11 英寸）",
  "A4 (210×297 mm)": "A4（210×297 mm）",
  "Paper format": "纸张规格",
  "Segmented circular markers (GCP / manual marking)":
    "分段圆形标志（地面控制点 / 人工标记）",
  "Chessboard (OpenCV Standard)": "棋盘格（OpenCV 标准）",
  "Target type": "标定板类型",
  "Target parameters": "标定板参数",
  "(intersection points).": "（即交点）。",
  "to preserve accurate measurements. For chessboards, inputs are":
    "打印，以保证测量精确。棋盘格的输入值为",
  "Generate high-precision printable calibration targets for camera calibration and photogrammetry. Print at":
    "生成可打印的高精度标定板，用于相机标定和摄影测量。请按",
  "The target generator script could not be loaded. Refresh and try again.":
    "标定板生成脚本加载失败，请刷新后重试。",
  "Initialization failed. Check console for details.":
    "初始化失败，详情请查看控制台。",
  "Calibration targets generator ready": "标定板生成器已就绪",
  "Download event dispatched": "已发出下载事件",
  "Generating PDF...": "正在生成 PDF…",
  "Cannot download: invalid segmented marker parameters":
    "无法下载：分段标志参数无效",
  "Cannot download: Invalid ring arcs parameters": "无法下载：圆弧环参数无效",
  "Cannot download: Invalid bullseye parameters": "无法下载：靶心标志参数无效",
  "Cannot download: Invalid chessboard parameters": "无法下载：棋盘格参数无效",
  "Preview event dispatched": "已发出预览事件",
  "Preview requested": "已请求预览",
  "Preview updated successfully": "预览已更新",
  "Invalid segmented marker parameters": "分段标志参数无效",
  "Invalid chessboard parameters": "棋盘格参数无效",
  "Initializing...": "正在初始化…",
  "For manual placement as ground control points or scale references. Agisoft Metashape detects only its own coded targets automatically; print those from Metashape (Tools → Markers → Print Markers).":
    "用于人工布设的地面控制点或尺度参考。Agisoft Metashape 只能自动识别它自己的编码标志，需要时请在 Metashape 中打印（Tools → Markers → Print Markers）。",
  "– disable “Fit to page”": "，并关闭“适合页面”",
  "OpenCV 检测的是": "OpenCV 检测的是",
};
