/** Chinese interface text for this tool (src/lib/i18n/toolText.js). */
export default {
  "No captured data yet. Start the camera to capture stereo images or depth maps.":
    "尚未采集数据。启动相机后即可采集双目图像或深度图。",
  "Captured data": "已采集的数据",
  "Session files": "会话文件",
  "Download ZIP": "下载 ZIP",
  "Save depth map": "保存深度图",
  "Compute depth": "计算深度",
  "Capture stereo": "采集双目图像",
  "Capture actions": "采集操作",
  Export: "导出",
  "Computed grayscale depth map": "计算得到的灰度深度图",
  "Depth map": "深度图",
  "Rectified right camera frame": "校正后的右相机画面",
  "Right eye": "右目",
  "Rectified left camera frame": "校正后的左相机画面",
  "Left eye": "左目",
  "Rectified views and depth": "校正视图与深度",
  Processing: "处理",
  "Live side-by-side stereo camera stream": "实时左右并排的双目视频流",
  "Original stream": "原始视频流",
  Input: "输入",
  "Live stereo views": "实时双目画面",
  "Sample ID": "样本编号",
  "Select a side-by-side stereo source. Device names may remain private until camera permission is granted.":
    "请选择左右并排输出的双目相机。授予相机权限前，设备名称可能不会显示。",
  Stop: "停止",
  "Start camera": "启动相机",
  Height: "高度",
  "Total width": "总宽度",
  "Detecting cameras…": "正在检测相机…",
  "Video device": "视频设备",
  "Camera access starts only after you choose Start camera.":
    "只有点击“启动相机”后才会访问摄像头。",
  "Camera configuration": "相机设置",
  "Capture setup": "采集设置",
  "Calibration profile:": "标定参数：",
  "Loading the stereo workspace…": "正在加载双目视觉工作台…",
  "System status": "系统状态",
};
