/** Chinese interface text for this tool (src/lib/i18n/toolText.js). */
export default {
  "Copy Text": "复制文本",
  "Save Edits & Get New Link": "保存修改并生成新链接",
  "Opened note content": "已打开的便签内容",
  "• 👁️ Read Only": "• 👁️ 只读",
  "• Expires:": "• 过期时间：",
  "Created:": "创建时间：",
  Close: "关闭",
  "Open Saved": "打开已保存的便签",
  Password: "密码",
  "Stored Note Name": "已保存的便签名称",
  "Or open a previously saved password-protected note below:":
    "或在下方打开之前保存的加密便签：",
  "Opening a shared link? It should load automatically.":
    "打开分享链接？它会自动加载。",
  Cancel: "取消",
  "Processing link...": "正在处理链接…",
  Unlock: "解锁",
  "Enter Password": "输入密码",
  "This note is password protected": "此便签受密码保护",
  "Open Note": "打开便签",
  "Anyone with a key-mode link can decrypt it. Password-mode links still require the password.":
    "任何持有密钥模式链接的人都能解密；密码模式的链接仍需输入密码。",
  "Generated Link": "生成的链接",
  "Reset form": "重置表单",
  "Copy Link": "复制链接",
  "Generate Share Link": "生成分享链接",
  "Advisory only.": "仅作提示。",
  "Read-only link": "只读链接",
  "Recipient must enter this": "接收者需要输入此密码",
  "Password Protection (Optional)": "密码保护（可选）",
  "Expires (Optional)": "过期时间（可选）",
  "Write your note here...": "在此输入便签内容…",
  Content: "内容",
  "e.g. Meeting Minutes": "如：会议纪要",
  "Note Name": "便签名称",
  "Create New Note": "新建便签",
  "✅ Saved & Regenerated link.": "✅ 已保存并生成新链接。",
  "❌ Copy failed. Select the text and copy it manually.":
    "❌ 复制失败，请选中文本后手动复制。",
  "✅ Link generated. Ready to share.": "✅ 链接已生成，可以分享了。",
  "Generating link...": "正在生成链接…",
  "❌ Wrong password or decryption failed.": "❌ 密码错误或解密失败。",
  "✅ Opened note by name/password.": "✅ 已按名称和密码打开便签。",
  "⚠️ Enter password.": "⚠️ 请输入密码。",
  "❌ Not a password-protected note.": "❌ 这不是受密码保护的便签。",
  "❌ No stored note found.": "❌ 未找到已保存的便签。",
  "⚠️ Enter note name.": "⚠️ 请输入便签名称。",
  "✅ Opened note with password.": "✅ 已用密码打开便签。",
  "⚠️ Enter the note password.": "⚠️ 请输入便签密码。",
  "❌ Unknown link mode.": "❌ 未知的链接模式。",
  "❌ Shared link missing key.": "❌ 分享链接缺少密钥。",
  "❌ Failed to decrypt.": "❌ 解密失败。",
  "✅ Opened note from link.": "✅ 已从链接打开便签。",
  "🔒 Protected note — password required.": "🔒 受保护的便签，需要密码。",
  "⚠️ This note has expired.": "⚠️ 此便签已过期。",
  "Untitled Note": "未命名便签",
  "⚠️ Note content must be {0} characters or fewer.":
    "⚠️ 便签内容不能超过 {0} 个字符。",
  "⚠️ Note name must be {0} characters or fewer.":
    "⚠️ 便签名称不能超过 {0} 个字符。",
  "Encryption happens in this browser. Shared data lives in the URL fragment; password-protected copies are kept only in this browser's local storage unless an optional backend is configured. Expiry and read-only flags are advisory, not revocation controls.":
    "加密在本浏览器中完成。分享的数据保存在 URL 片段中；带密码的副本只保存在本浏览器的本地存储里（除非另行配置了后端）。过期和只读标记仅作提示，不能用于撤销访问。",
};
