/** Chinese interface text for this tool (src/lib/i18n/toolText.js). */
export default {
  "Waiting for an abstract…": "等待输入摘要…",
  "View raw AI response": "查看 AI 原始返回",
  "Complete journal comparison table": "完整的期刊对比表",
  "View all evaluation fields": "查看全部评价字段",
  "Verify:": "核对：",
  "Recommended journals": "推荐期刊",
  Results: "结果",
  "Alignment:": "契合度：",
  "Abstract recap:": "摘要回顾：",
  "AI summary": "AI 总结",
  "Download CSV": "下载 CSV",
  "Build a journal shortlist": "生成期刊候选清单",
  "Evaluation fields": "评价字段",
  "Indicator reference": "指标参考",
  "Journal analysis model": "期刊分析模型",
  "AI model configuration": "AI 模型设置",
  "e.g., need open data compliance, avoiding page charges, prefer Q1.":
    "如：需要符合开放数据要求、避免版面费、优先 Q1。",
  "Special notes": "特殊要求",
  "Suggestions (3–8)": "推荐数量（3–8）",
  "Journal type": "期刊类型",
  "Review speed": "审稿速度",
  "OA requirement": "开放获取要求",
  "Keywords / Focus": "关键词 / 研究重点",
  "Submission profile": "投稿偏好",
  "Paste a 200–400 word abstract covering objective, method, data, and novelty.":
    "粘贴 200–400 词的摘要，涵盖研究目的、方法、数据和创新点。",
  Abstract: "摘要",
  "Recommended 200–400 words": "建议 200–400 词",
  "Research abstract": "研究摘要",
  "Manuscript and journal preferences": "稿件与期刊偏好",
  "Generation failed": "生成失败",
  "AI response could not be parsed. Please adjust the prompt or try again.":
    "无法解析 AI 返回结果。请调整输入后重试。",
  "Calling AI…": "正在调用 AI…",
  "Preparing prompt…": "正在准备提示词…",
  "Please paste the abstract first.": "请先粘贴摘要。",
  "fetch failed": "请求失败",
  "NLM Catalog": "NLM Catalog",
  "Any alerts or risk flags": "需要注意的警示或风险",
  "Warning Status": "预警状态",
  "Tailored recommendations": "针对性的投稿建议",
  "Submission Advice": "投稿建议",
  "Competitive advantages": "竞争优势",
  Strengths: "优势",
  "Unique columns or sections": "特色栏目或版块",
  "Special Sections": "特色栏目",
  "Key topics or domains": "重点主题或领域",
  "Core Focus Areas": "核心关注领域",
  "Primary research area": "主要研究领域",
  "Discipline Scope": "学科范围",
  "Time from acceptance to publication": "录用到出版的时间",
  "Publication Timeline": "出版周期",
  "Full peer review cycle": "完整的同行评审周期",
  "Submission-to-Acceptance (weeks)": "投稿到录用（周）",
  "Desk review duration": "初审时长",
  "Initial Review Cycle (weeks)": "初审周期（周）",
  "Estimated acceptance probability": "估计录用概率",
  "Acceptance Rate (%)": "录用率（%）",
  "Articles published per year": "每年发表文章数",
  "Annual Publications": "年发文量",
  "Percentage of self-citations": "自引比例",
  "Self-citation Rate (%)": "自引率（%）",
  "Scopus or Google Scholar H-index": "Scopus 或 Google Scholar H 指数",
  "Scopus CiteScore": "Scopus CiteScore",
  "Chinese Academy of Sciences division": "中国科学院分区",
  "CAS Quartile": "中科院分区",
  "Q1–Q4 ranking": "Q1–Q4 排名",
  "JCR Quartile": "JCR 分区",
  "Five-year IF": "五年影响因子",
  "Five-year Impact Factor": "五年影响因子",
  "Latest Journal Impact Factor": "最新期刊影响因子",
  "Impact Factor (2024)": "影响因子（2024）",
  "Article processing charge": "文章处理费",
  "OA Fee (USD)": "OA 费用（美元）",
  "Gold / Hybrid / Subscription": "金色 / 混合 / 订阅",
  "Open Access (OA)": "开放获取（OA）",
  "Monthly / Quarterly / Continuous etc.": "月刊 / 季刊 / 连续出版等",
  "Publication Frequency": "出版频率",
  "Year the journal was founded": "期刊创刊年份",
  "Year Established": "创刊年份",
  "Publishing group or organization": "出版集团或机构",
  Publisher: "出版社",
  "Print or electronic ISSN": "印刷版或电子版 ISSN",
  "Official full name": "官方全称",
  "Journal Name": "期刊名称",
  "Auto-increment ranking (1,2,3...)": "自动递增编号（1、2、3…）",
  "Serial Number": "序号",
  "Prefer SCI / international English journals": "优先 SCI / 国际英文期刊",
  "Prefer Chinese core journals (CSCD/PKU core)":
    "优先中文核心期刊（CSCD / 北大核心）",
  "No preference (Chinese or international)": "不限（中文或国际期刊均可）",
  "Subscription journal preferred": "优先订阅期刊",
  "Open access required": "必须开放获取",
  "No preference (OA or subscription)": "不限（开放获取或订阅均可）",
  "Publisher not provided": "未提供出版社",
  "Generate journal plan": "生成期刊方案",
  "Generating…": "正在生成…",
  "The indicator file is missing, so the default journal evaluation schema is used.":
    "指标文件缺失，已使用默认的期刊评价体系。",
  "Each suggested journal is scored against these fields. The full indicator schema is sent with your request.":
    "每个推荐期刊都会按这些字段评分；完整的指标体系会随请求一并发送。",
  "Flexible / not specified": "灵活 / 未指定",
  "Candidate Journal {0}": "候选期刊 {0}",
  "Generated {0} journal suggestions.": "已生成 {0} 条期刊建议。",
  "Journal suggestions and the metrics shown with them come from the language model and are not looked up in a database. Each result links to SCImago, the NLM Catalog and DOAJ for checking; confirm impact factor and quartiles in Journal Citation Reports and fees and review times on the publisher's site before submission.":
    "期刊推荐及其指标由大语言模型给出，并未查询数据库。每条结果都附有 SCImago、NLM Catalog 和 DOAJ 链接供核对；投稿前请在 Journal Citation Reports 中确认影响因子和分区，在出版社网站确认费用和审稿周期。",
  "e.g., precision agriculture; hyperspectral imaging; maize":
    "如：精准农业；高光谱成像；玉米",
};
