/** Chinese interface text for this tool (src/lib/i18n/toolText.js). */
export default {
  "Group comparison needs at least two groups with two or more values each.":
    "组间比较至少需要两个组，且每组至少有两个数值。",
  "One-way ANOVA (computed from all rows): F({0}, {1}) = {2}, {3}.":
    "单因素方差分析（基于全部数据计算）：F({0}, {1}) = {2}，{3}。",
  "Letters: Tukey–Kramer HSD at α = 0.05; groups sharing a letter do not differ significantly.":
    "字母标记：Tukey–Kramer HSD 检验，α = 0.05；共享同一字母的组之间差异不显著。",
  "Error bars: mean ± SE.": "误差线：均值 ± 标准误。",
  "Correlation heatmap across numeric columns.": "数值列之间的相关性热图。",
  "Raw AI response": "AI 原始返回",
  "Upload a table and generate a visualization to see it here.":
    "上传表格并生成可视化后，图表会显示在这里。",
  "No chart yet": "暂无图表",
  "Download PNG": "下载 PNG",
  "Interactive chart": "交互图表",
  "Run an analysis to see highlights here.": "运行分析后，要点会显示在这里。",
  "Summary:": "摘要：",
  "AI Insights": "AI 洞察",
  "No data preview yet.": "暂无数据预览。",
  "Preview of the uploaded dataset": "上传数据预览",
  "rows)": "行）",
  "Preview (first": "预览（前",
  "Dataset summary that will be sent to the selected AI provider":
    "将发送给所选 AI 服务的数据摘要",
  "Dataset summary sent to AI": "发送给 AI 的数据摘要",
  "Analysis model": "分析模型",
  "Apply field mapping": "应用字段映射",
  "Offline visualization.": "离线可视化。",
  "Side-by-side multi charts": "并排显示多图",
  "Error Bars": "误差线",
  Aggregation: "汇总方式",
  None: "无",
  Group: "分组",
  Auto: "自动",
  "Y Field": "Y 字段",
  "X Field": "X 字段",
  "Tell the AI what kind of pattern or story to highlight.":
    "告诉 AI 你希望突出哪种规律或结论。",
  "Analysis goal": "分析目标",
  "Step 2": "第 2 步",
  "Analysis goal & API": "分析目标与 API",
  "Excel sheet": "Excel 工作表",
  "Choose a CSV, TSV, XLSX, XLS or JSON file":
    "选择 CSV、TSV、XLSX、XLS 或 JSON 文件",
  "Step 1": "第 1 步",
  "Upload data": "上传数据",
  "AI did not return a summary.": "AI 未返回摘要。",
  "AI response was not valid JSON.": "AI 返回的不是有效 JSON。",
  "Analysis failed.": "分析失败。",
  "AI call failed.": "AI 调用失败。",
  "Local fallback visualization.": "本地备用可视化。",
  "Visualization ready!": "可视化已生成！",
  "Calling AI…": "正在调用 AI…",
  "Local visualization generated from the uploaded rows.":
    "已根据上传的数据在本地生成可视化。",
  "Local deterministic visualization.": "本地确定性可视化。",
  "The uploaded table does not contain a usable numeric series.":
    "上传的表格中没有可用的数值列。",
  "Building prompt…": "正在构建提示词…",
  "Please upload a CSV or TSV file first.": "请先上传 CSV 或 TSV 文件。",
  "Failed to read file. Please try again.": "读取文件失败，请重试。",
  "File ready. Configure the analysis prompt.": "文件已就绪，请设置分析目标。",
  "JSON parse failed. Treating as text.": "JSON 解析失败，按文本处理。",
  "Failed to load Excel parser.": "Excel 解析器加载失败。",
  "Failed to parse Excel file.": "Excel 文件解析失败。",
  "Reading file…": "正在读取文件…",
  "File is larger than 20 MB. Please reduce it before analysis.":
    "文件超过 20 MB，请缩小后再分析。",
  "Chart rendering failed.": "图表渲染失败。",
  "No response yet.": "尚无返回。",
  "Generate visualization": "生成可视化",
  "Analyzing…": "正在分析…",
  "Sequence of {0}.": "{0} 的序列。",
  "Mean {0} by {1}.": "按 {1} 分组的 {0} 均值。",
  "Histogram of {0}.": "{0} 的直方图。",
  "Violin of {0} by {1}.": "按 {1} 分组的 {0} 小提琴图。",
  "Distribution of {0} by {1}.": "按 {1} 分组的 {0} 分布。",
  "Grouped boxplot + violin of {0} by {1}":
    "按 {1} 分组的 {0} 箱线图 + 小提琴图",
  "Scatter of {0} vs {1}.": "{0} 与 {1} 的散点图。",
  "Scatter of {0} vs {1} + histogram": "{0} 与 {1} 的散点图 + 直方图",
  "The suggested chart could not be built from this table; set the X and Y fields manually and retry.":
    "无法根据这张表格生成所推荐的图表；请手动设置 X 和 Y 字段后重试。",
  "Grouped Boxplot of {0}": "{0} 的分组箱线图",
  "Mean {0} by {1}": "按 {1} 分组的 {0} 均值",
  "Histogram of {0}": "{0} 的直方图",
  "Grouped Violin of {0}": "{0} 的分组小提琴图",
  "Violin of {0}": "{0} 的小提琴图",
  Boxplot: "箱线图",
  "Correlation Heatmap": "相关性热图",
  "Upload a CSV/TSV to get started.": "上传 CSV/TSV 文件即可开始。",
  "{0} vs {1}": "{0} 与 {1}",
  "{0} by {1}": "按 {1} 的 {0}",
  "{0}({1}) by {2} grouped by {3}": "按 {2}、并以 {3} 分组的 {0}({1})",
  "{0}({1}) by {2} grouped + violin": "按 {2} 分组的 {0}({1}) + 小提琴图",
  "{0}({1}) by {2}": "按 {2} 的 {0}({1})",
  "{0}({1}) by {2} + histogram": "按 {2} 的 {0}({1}) + 直方图",
};
