/** Chinese interface text for this tool (src/lib/i18n/toolText.js). */
export default {
  "Center step (m, 0 = auto)": "中心间距（m，0 = 自动）",
  "to get download links.": "获取下载链接。",
  Generate: "生成",
  "to refresh → click": " 刷新 → 点击",
  Preview: "预览",
  "Upload KML → set parameters → click": "上传 KML → 设置参数 → 点击",
  "Preview of the uploaded field polygon and generated CCO flight route":
    "上传的田块多边形与生成的 CCO 航线预览",
  "Live Preview": "实时预览",
  "Download cco_full.kmz": "下载 cco_full.kmz",
  "Download waylines.wpml": "下载 waylines.wpml",
  "Download template.kml": "下载 template.kml",
  Idle: "空闲",
  "Generate files": "生成文件",
  "Reads device enums from a KMZ up to 25 MB. Imported values still require verification.":
    "可从不超过 25 MB 的 KMZ 中读取设备枚举值，导入后仍需核对。",
  "Parse Drone & Payload": "解析无人机与负载",
  "Upload DJI route (.kmz)": "上传大疆航线文件（.kmz）",
  "Import from DJI KMZ": "从大疆 KMZ 导入",
  "Max points / part": "每段最大航点数",
  "Drone & Payload (Optional)": "无人机与负载（可选）",
  "File suffix": "文件名后缀",
  "Gimbal pitch (°)": "云台俯仰角（°）",
  "Speed (m/s)": "速度（m/s）",
  "Altitude (m)": "高度（m）",
  "Flight & Camera": "飞行与相机",
  No: "否",
  Yes: "是",
  "Prune outside centers": "剔除区域外的圆心",
  "Clip inside": "仅保留区域内航点",
  "BBox center": "包围框中心",
  Centroid: "质心",
  "Center mode": "中心模式",
  "Start bearing (°)": "起始方位角（°）",
  "Grid bearing (°)": "网格方位角（°）",
  "Padding (m)": "外扩距离（m）",
  "Overlap (0~0.9)": "重叠率（0~0.9）",
  "Pts/circle": "每圈航点数",
  "Circle radius (m)": "环绕半径（m）",
  "Coverage Parameters": "覆盖参数",
  "One Polygon is supported. Maximum file size: 5 MB.":
    "仅支持一个多边形，文件不超过 5 MB。",
  "Upload KML (Polygon)": "上传 KML（多边形）",
  "Target Area": "目标区域",
  "Validate altitude, route geometry, device enums and local flight rules in DJI software before operating an aircraft.":
    "操作飞机前，请在大疆软件中核对高度、航线几何、设备枚举值以及当地飞行规定。",
  "Planning preview.": "规划预览。",
};
