/**
 * Standard data types exchanged between App Lab tools
 * (design/DESIGN_SPEC.md §10.3). Tools declare them in appManifest.js as
 * `inputs` / `outputs`; matching types drive the "next step" suggestions.
 */
export const DATA_TYPES = {
  "geo.point": { en: "Location", zh: "位置" },
  "geo.point[]": { en: "GPS points", zh: "GPS 点集" },
  "geo.polygon": { en: "Field boundary", zh: "田块边界" },
  "table.timeseries": { en: "Time series table", zh: "时间序列表" },
  table: { en: "Data table", zh: "数据表" },
  image: { en: "Image", zh: "图像" },
  "image.set": { en: "Image set", zh: "图像集" },
  document: { en: "Document", zh: "文档" },
  text: { en: "Text", zh: "文本" },
};

export const MATURITY = {
  stable: {
    en: "Stable",
    zh: "稳定",
    hint: {
      en: "Core computations validated against independent references (stated for each tool); results can be used in research.",
      zh: "核心计算已用独立基准验证（各工具注明依据），结果可用于科研。",
    },
  },
  beta: {
    en: "Beta",
    zh: "测试中",
    hint: {
      en: "Works end to end; one step still awaits validation (stated for each tool).",
      zh: "功能完整可用，尚有一个环节待验证（各工具注明）。",
    },
  },
  experimental: {
    en: "Experimental",
    zh: "实验性",
    hint: {
      en: "Output is generated by a language model; check it before use.",
      zh: "输出由大语言模型生成，使用前请核对。",
    },
  },
};
